-keep class com.signalsticker.maker.signal.StickerPackProto { *; }
-keep class com.signalsticker.maker.signal.StickerPackProto$* { *; }
-keep class com.signalsticker.maker.signal.StickerCrypto { *; }
-keep class com.signalsticker.maker.signal.StickerPackEncoder { *; }
